// <auto-generated />
using System;
using EF_Demo1.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EF_Demo1.Migrations
{
    [DbContext(typeof(TestDB))]
    [Migration("20211122143929_StillTryingToFixFriendsList5")]
    partial class StillTryingToFixFriendsList5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EF_Demo1.Models.HiScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("HiScores");
                });

            modelBuilder.Entity("EF_Demo1.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Player.Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Player.Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("EF_Demo1.Models.HiScore", b =>
                {
                    b.HasOne("EF_Demo1.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("EF_Demo1.Models.Player", b =>
                {
                    b.HasOne("EF_Demo1.Models.Player", null)
                        .WithMany("Friends")
                        .HasForeignKey("Player.Id");
                });

            modelBuilder.Entity("EF_Demo1.Models.Player", b =>
                {
                    b.Navigation("Friends");
                });
#pragma warning restore 612, 618
        }
    }
}
